### ISSUE TITLE
/map topic not being modified

### ISSUE THREAD

**Issue by LadyZayin** [tu-darmstadt-ros-pkg/mapstitch#1]
Hi,

I am trying to use your package to align two occupancy grids, one generated by slam gmapping and the other representing the real world map from the Stage simulator. When I'm executing "rosrun mapstitch ros_mapstitch", I assume that the /map topic should be transformed in real time according to the world map, is that right?

I've encountered two issues. First, nothing is being published on the /world and /align topics. To solve this problem, I've extracted the world occupancy grid from Stage and published it on both /world and /align topics. The second problem arose at this point; the /map remains the same as if no transform was being applied. Therefore, it seems like mapstitch isn't modifying it. Besides, I've tried the debug option by setting the parameter to true, but no pgm is being outputted. What do you think could be the problem here? 

Moreover, what node did you intend to be publishing on /world and /align? I highly doubt my solution is appropriate since the Stage map is significantly different from the slam map. 

Thanks!

**Comment by pscholl** [comment]
There are actually three things that are causing the problems you encountered.

Maptstitcher does not modify any maps! It only broadcasts a transform between the "map" <-> "world" frames. And it broadcast this transform only when the /map topic receives an update. At and only at this time the debug.pgm files are written (in the working directory of the ros mapstitch process, usually somewhere under ~/.ros/).

Now the transform is calculated as the transform to match the /world and /align map on top of each other. This way you can setup a system that works with "pre-build" maps. In any other case you have to map the /align topic to the /map topic, and publish a "global" map on the /world topic. For those maps you need to set the frame_id! Because the transform is published between those frames (I simply assumed they are set to "map" and "world" previously).

Long story, short: only a transform between the /world's frame_id and /align's frame_id is broadcast (you can see this in rviz and align maps there). This is only done when there is an update on the /map topic.

For your setup, publish a "global" map on /world with the frame_id set to "world", map the /align topic to the /map topic, and the maps should be aligned as soon as both /world and /map can be matched on top of each other by rotation and shifting. I used the map_server component to publish the static "world"-map in my setups.

**Comment by LadyZayin** [comment]
Thank you for your quick reply. This helps a lot!

I have another question on the side, feel free to ignore it. When I publish a pgm using map_server, then run stage with slam gmapping to generate a /map, the /world map doesn't have the same size and resolution as /map. However, I did set the size & resolution of gmapping to be the same as the world's. Would you know what may be causing this?

**Comment by pscholl** [comment]
No, haven't used gmapping that much. You could however get around the same-size limitation by hacking the stitcher (it might even work out of the box, but that depends on the stitching implementation in opencv that's being used). However the resolution needs to be the same.

**Comment by LadyZayin** [comment]
Thank you for your help!
